# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(861, 414)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(861, 414))
        MainWindow.setMaximumSize(QtCore.QSize(861, 414))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        self.portLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.portLabel.setFont(font)
        self.portLabel.setAutoFillBackground(False)
        self.portLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.portLabel.setObjectName("portLabel")
        self.verticalLayout.addWidget(self.portLabel)
        self.port = QtWidgets.QLineEdit(self.centralwidget)
        self.port.setAlignment(QtCore.Qt.AlignCenter)
        self.port.setReadOnly(True)
        self.port.setObjectName("port")
        self.verticalLayout.addWidget(self.port)
        self.stopbitLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.stopbitLabel.setFont(font)
        self.stopbitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopbitLabel.setObjectName("stopbitLabel")
        self.verticalLayout.addWidget(self.stopbitLabel)
        self.stopbit = QtWidgets.QLineEdit(self.centralwidget)
        self.stopbit.setAlignment(QtCore.Qt.AlignCenter)
        self.stopbit.setReadOnly(True)
        self.stopbit.setObjectName("stopbit")
        self.verticalLayout.addWidget(self.stopbit)
        self.baudrateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.baudrateLabel.setFont(font)
        self.baudrateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.baudrateLabel.setObjectName("baudrateLabel")
        self.verticalLayout.addWidget(self.baudrateLabel)
        self.baudrate = QtWidgets.QLineEdit(self.centralwidget)
        self.baudrate.setAlignment(QtCore.Qt.AlignCenter)
        self.baudrate.setReadOnly(True)
        self.baudrate.setObjectName("baudrate")
        self.verticalLayout.addWidget(self.baudrate)
        self.parityLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.parityLabel.setFont(font)
        self.parityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parityLabel.setObjectName("parityLabel")
        self.verticalLayout.addWidget(self.parityLabel)
        self.parity = QtWidgets.QLineEdit(self.centralwidget)
        self.parity.setAlignment(QtCore.Qt.AlignCenter)
        self.parity.setReadOnly(True)
        self.parity.setObjectName("parity")
        self.verticalLayout.addWidget(self.parity)
        self.databitsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.databitsLabel.setFont(font)
        self.databitsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.databitsLabel.setObjectName("databitsLabel")
        self.verticalLayout.addWidget(self.databitsLabel)
        self.databits = QtWidgets.QLineEdit(self.centralwidget)
        self.databits.setAlignment(QtCore.Qt.AlignCenter)
        self.databits.setReadOnly(True)
        self.databits.setObjectName("databits")
        self.verticalLayout.addWidget(self.databits)
        self.unitLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.unitLabel.setFont(font)
        self.unitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLabel.setObjectName("unitLabel")
        self.verticalLayout.addWidget(self.unitLabel)
        self.unitBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unitBox.setFont(font)
        self.unitBox.setObjectName("unitBox")
        self.unitBox.addItem("")
        self.unitBox.addItem("")
        self.unitBox.addItem("")
        self.unitBox.addItem("")
        self.verticalLayout.addWidget(self.unitBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.terminal = QtWidgets.QTextEdit(self.tab)
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.gridLayout_3.addWidget(self.terminal, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUART = QtWidgets.QAction(MainWindow)
        self.actionUART.setObjectName("actionUART")
        self.actionGraph = QtWidgets.QAction(MainWindow)
        self.actionGraph.setObjectName("actionGraph")
        self.menuSettings.addAction(self.actionUART)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.unitBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI"))
        self.portLabel.setText(_translate("MainWindow", "Port:"))
        self.stopbitLabel.setText(_translate("MainWindow", "Stop bit:"))
        self.baudrateLabel.setText(_translate("MainWindow", "Baud rate:"))
        self.parityLabel.setText(_translate("MainWindow", "Parity:"))
        self.databitsLabel.setText(_translate("MainWindow", "Data bits:"))
        self.unitLabel.setText(_translate("MainWindow", "Select unit:"))
        self.unitBox.setItemText(0, _translate("MainWindow", "Temperature"))
        self.unitBox.setItemText(1, _translate("MainWindow", "None"))
        self.unitBox.setItemText(2, _translate("MainWindow", "Pressure"))
        self.unitBox.setItemText(3, _translate("MainWindow", "Irradiance"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Terminal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Graph"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionUART.setText(_translate("MainWindow", "UART"))
        self.actionUART.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionGraph.setText(_translate("MainWindow", "Graph"))
        self.actionGraph.setShortcut(_translate("MainWindow", "Ctrl+G"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
